### ISSUE TITLE
A few UI issues

### ISSUE THREAD

**Issue by GaurabAryal** [jeremyukim/focus-react#11]
- [x] [Pomodoro box ](https://i.imgur.com/OXDa5hM.png)
- [x] [Footer](https://i.imgur.com/pYHdwlQ.png)
- [x] [Tasks](https://i.imgur.com/hEaq0JS.png) 
 
If I recall correctly, the tasks are supposed to be under the text box "What needs to be done?"

Thanks a lot! 😄 ❤️

**Comment by GaurabAryal** [comment]
Love the new update! Thanks again!

**Comment by jeremyukim** [comment]
Thanks for the help 😍😍
